name: Build and push docker images
on:
  push:
    branches:
      - development
    paths:
      - "task_3/dockerfiles/**"

permissions:
  id-token: write
  contents: read

env:
  ECR_REGISTRY: ${{secrets.AWS_ARN}}.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get aws access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ARN}}:role/Actions-ECR
          aws-region: us-east-1

      - name: Login to ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check commit effect
        run: |
          CHANGED_DOCKERFILES=$(git diff --name-only "${{github.event.before}}" "${{github.sha}}" | grep '^task_3/dockerfiles/' | cut -d/ -f3 | sort -u)
          echo "IMAGES_LIST=$CHANGED_DOCKERFILES" >> "$GITHUB_ENV"

      - name: Build and push modified images
        run: |
          for image in $IMAGES_LIST; do
            echo "Cooking la $image"
            docker build -t "$ECR_REGISTRY/practice/${image,,}:${{github.run_number}}" "task_3/dockerfiles/$image"  &&
            docker push "$ECR_REGISTRY/practice/${image,,}:${{github.run_number}}" && echo "La $image est pret"
          done