name: Build and Push Docker Images
on:
  push:
    branches:
      - development
    paths:
      - "task_3/dockerfiles/**"
      - ".github/workflows/docker-builder.yml"

permissions:
  id-token: write
  contents: read

env:
  ECR_REGISTRY: ${{secrets.AWS_ARN}}.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get aws access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ARN}}:role/Actions-ECR
          aws-region: us-east-1

      - name: Login to ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check commit effect
        run: |
          CHANGED_DOCKERFILES=$(git diff --name-only HEAD^ HEAD | grep '^task_3/dockerfiles/' | cut -d/ -f1-3)
          
          echo "$CHANGED_DOCKERFILES"